//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.18 at 02:46:54 PM CET 
//


package org.nuxeo.jaxb;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.nuxeo.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.nuxeo.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Component }
     * 
     */
    public Component createComponent() {
        return new Component();
    }

    /**
     * Create an instance of {@link Component.Extension }
     * 
     */
    public Component.Extension createComponentExtension() {
        return new Component.Extension();
    }

    /**
     * Create an instance of {@link Component.Extension.Handler }
     * 
     */
    public Component.Extension.Handler createComponentExtensionHandler() {
        return new Component.Extension.Handler();
    }

    /**
     * Create an instance of {@link Component.Extension.Chain }
     * 
     */
    public Component.Extension.Chain createComponentExtensionChain() {
        return new Component.Extension.Chain();
    }

    /**
     * Create an instance of {@link Component.Extension.Chain.Operation }
     * 
     */
    public Component.Extension.Chain.Operation createComponentExtensionChainOperation() {
        return new Component.Extension.Chain.Operation();
    }

    /**
     * Create an instance of {@link Component.Extension.Action }
     * 
     */
    public Component.Extension.Action createComponentExtensionAction() {
        return new Component.Extension.Action();
    }

    /**
     * Create an instance of {@link Component.Extension.Action.Filter }
     * 
     */
    public Component.Extension.Action.Filter createComponentExtensionActionFilter() {
        return new Component.Extension.Action.Filter();
    }

    /**
     * Create an instance of {@link Component.Extension.Action.Filter.Rule }
     * 
     */
    public Component.Extension.Action.Filter.Rule createComponentExtensionActionFilterRule() {
        return new Component.Extension.Action.Filter.Rule();
    }

    /**
     * Create an instance of {@link Component.Extension.Doctype }
     * 
     */
    public Component.Extension.Doctype createComponentExtensionDoctype() {
        return new Component.Extension.Doctype();
    }

    /**
     * Create an instance of {@link Component.Extension.Type }
     * 
     */
    public Component.Extension.Type createComponentExtensionType() {
        return new Component.Extension.Type();
    }

    /**
     * Create an instance of {@link Component.Extension.Type.ContentViews }
     * 
     */
    public Component.Extension.Type.ContentViews createComponentExtensionTypeContentViews() {
        return new Component.Extension.Type.ContentViews();
    }

    /**
     * Create an instance of {@link Component.Extension.Type.Layouts }
     * 
     */
    public Component.Extension.Type.Layouts createComponentExtensionTypeLayouts() {
        return new Component.Extension.Type.Layouts();
    }

    /**
     * Create an instance of {@link Component.Extension.Schema }
     * 
     */
    public Component.Extension.Schema createComponentExtensionSchema() {
        return new Component.Extension.Schema();
    }

    /**
     * Create an instance of {@link Component.Extension.Handler.Filters }
     * 
     */
    public Component.Extension.Handler.Filters createComponentExtensionHandlerFilters() {
        return new Component.Extension.Handler.Filters();
    }

    /**
     * Create an instance of {@link Component.Extension.Chain.Operation.Param }
     * 
     */
    public Component.Extension.Chain.Operation.Param createComponentExtensionChainOperationParam() {
        return new Component.Extension.Chain.Operation.Param();
    }

    /**
     * Create an instance of {@link Component.Extension.Action.Filter.Rule.Type }
     * 
     */
    public Component.Extension.Action.Filter.Rule.Type createComponentExtensionActionFilterRuleType() {
        return new Component.Extension.Action.Filter.Rule.Type();
    }

    /**
     * Create an instance of {@link Component.Extension.Doctype.Schema }
     * 
     */
    public Component.Extension.Doctype.Schema createComponentExtensionDoctypeSchema() {
        return new Component.Extension.Doctype.Schema();
    }

    /**
     * Create an instance of {@link Component.Extension.Doctype.Facet }
     * 
     */
    public Component.Extension.Doctype.Facet createComponentExtensionDoctypeFacet() {
        return new Component.Extension.Doctype.Facet();
    }

    /**
     * Create an instance of {@link Component.Extension.Type.Subtypes }
     * 
     */
    public Component.Extension.Type.Subtypes createComponentExtensionTypeSubtypes() {
        return new Component.Extension.Type.Subtypes();
    }

    /**
     * Create an instance of {@link Component.Extension.Type.ContentViews.ContentView }
     * 
     */
    public Component.Extension.Type.ContentViews.ContentView createComponentExtensionTypeContentViewsContentView() {
        return new Component.Extension.Type.ContentViews.ContentView();
    }

    /**
     * Create an instance of {@link Component.Extension.Type.Layouts.Layout }
     * 
     */
    public Component.Extension.Type.Layouts.Layout createComponentExtensionTypeLayoutsLayout() {
        return new Component.Extension.Type.Layouts.Layout();
    }

}
